### ISSUE TITLE
Resource not found for the segment...

### ISSUE THREAD

**Issue by bwmodular** [thomasdayman/PCF_SimpleNoteExperience#1]
HI there,
we've attached the PCF to attributes on two different entities. It works fine on one, but on the other we get this error message when trying to upload a file.
![image](https://user-images.githubusercontent.com/1889586/125060995-cd62e180-e0a4-11eb-9215-79a33931c12f.png)

The only thing we can think of is that the issue is with the plural of the name.
On the entity that works (inspection) the plural is inspections, wheras on the entity that does not work (nonconformity) the plural is 'Non Conformities' (not as in the screenshot 'nonconformitys'). But that could be nothing to do with it. Any ideas?

Thanks,
Ben

**Comment by bwmodular** [comment]
Looking at the code, I think this line is causing the problem (line 392):
`entity["objectid_" + entityName + "@odata.bind"] = "/" + entityName + "s(" + entityId + ")";`

It's assuming that the plural name of the entity is the entity name with an 's' on the name, whereas for this entity the plural name of van_nonconformity is van_nonconformities. I think the only way to fix this would be to do a metadata request to get the correct plural name of the entity before uploading the file.

**Comment by thomasdayman** [comment]
Hi bwmodular, I will try and resolve this problem as soon as possible.

Thanks for your previous responses!

**Comment by bwmodular** [comment]
Hi @thomasdayman, thanks for the reply.
It's not urgent for us that you fix it, but glad that you will look at it at some point. (Sorry, no time to submit a PR myself at the moment).
Thanks for the great tool - it has proved very useful to us....

**Comment by bwmodular** [comment]
If you do have time to look at it, I think fetching the entity's formal name using the WebApi should be relatively straightforward - something like this:
https://foo.crm11.dynamics.com/api/data/v9.2/EntityDefinitions(LogicalName='account')?$select=LogicalCollectionName

**Comment by thomasdayman** [comment]
I have added a fix to the index.ts file which now gets the plural name of the entity. I have tested it and it looks like it is working correctly now.

I have created a new managed solution in the 'Releases' folder. Please let me know if it has fixed the issue.

**Comment by bwmodular** [comment]
That's brilliant - we'll test and get back to you ASAP. Thanks!

**Comment by bwmodular** [comment]
Hiya, I'm afraid we are still getting the same issue. Let me know if I can give you any more information? Thanks again

**Comment by thomasdayman** [comment]
Thanks for checking. 

I think I will need more information. I have just retested again in my environment and it is working on my side. Have you deleted the previous managed solution and imported the new one?

**Comment by bwmodular** [comment]
I've not deleted the previous managed solution because we are using it with other entities which have a 'normal' plural form, so I can't delete it due to the dependencies. Looking in the source code in the solution, I can see the 'GetEntityPluralName' method, so I definitely have your latest version. I can try deleting the managed solution in another environment and see if re-importing it makes any difference. I'll also try a private browsing session in case something is getting cached....

**Comment by bwmodular** [comment]
So, I created a new entity with the same name ('Non Conformity' / 'Non Conformities') from scratch in my new power apps developer instance.
Added it to a Model Driven App, uploaded the latest version of your solution, added the Control to a single line of text field on the form. Look what happens:
https://user-images.githubusercontent.com/1889586/125534369-afe5a851-87a4-4834-89aa-85946f8f06b4.mp4
Very odd - completely different behaviour than before....

**Comment by thomasdayman** [comment]
Have you enabled the timeline for the entity?

**Comment by bwmodular** [comment]
So sorry, I hadn't! Now I've enabled it, it's working fine in my developer environment. So now, I just need to work out why it's not working in my other environment. Thanks so much for fixing this - happy to close this issue if you are...

**Comment by bwmodular** [comment]
Hi again, I know this issue is closed now, but I found out why the new version was still not working in an environment which had the old version installed. A colleague told me that when you release a new version of a PCF, you have to increase the version in the file 'ControlManifest.xml'.
I changed the version in my local copy to 1.0.1 and re-imported the solution and this fixed the problem I was having. I think it must cache previous versions unless it sees that the version in the manifest has been updated. Good to know....
Thanks again,
Ben

**Comment by thomasdayman** [comment]
Hi Ben,

Apologies as you are right I did forget to update the version number.

I'm glad that its working for you now :)
